/* ACTION TYPES */

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';

export const ADD_TRANSACTION_REQUEST = 'ADD_TRANSACTION_REQUEST';
export const ADD_TRANSACTION_SUCCESS = 'ADD_TRANSACTION_SUCCESS';
export const ADD_TRANSACTION_FAILURE = 'ADD_TRANSACTION_FAILURE';

export const REMOVE_TRANSACTION_REQUEST = 'REMOVE_TRANSACTION_REQUEST';
export const REMOVE_TRANSACTION_SUCCESS = 'REMOVE_TRANSACTION_SUCCESS';
export const REMOVE_TRANSACTION_FAILURE = 'REMOVE_TRANSACTION_FAILURE';

export const SELECT_TRANSACTION = 'SELECT_TRANSACTION';
export const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION';

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
